### ISSUE TITLE
import skimage.io?

### ISSUE THREAD

**Issue by SinclairHudson** [llSourcell/tensorflow_speech_recognition_demo#22]
I'm having trouble locating where I can download scikit (I think that's what I need). Can someone point me in the right direction? I'm using python 3.5.2 64-bit windows 10. Thanks! Here is the error message:
Traceback (most recent call last):
  File "C:\Users\--------\Desktop\listen\demo.py", line 3, in <module>
    import speech_data
  File "C:\Users\--------\Desktop\listen\speech_data.py", line 11, in <module>
    import skimage.io  # scikit-image
ImportError: No module named 'skimage'

**Comment by hazelwolf** [comment]
_pip install scikit-image_ if you are unable to install through pip then download the package here https://pypi.python.org/pypi/scikit-image and pip install packagename.
