### ISSUE TITLE
Traceback demo.py line 15, and urllib.error.URLError

### ISSUE THREAD

**Issue by ayaanp-dev** [llSourcell/tensorflow_speech_recognition_demo#31]
Hi, I have an error saying, `urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>.`  I have an Traceback error saying,
`Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    X, Y = next(batch).`

The screenshot of my screen in Command Prompt is here.

<img width="947" alt="errorspeechrecognition" src="https://user-images.githubusercontent.com/31377115/47966727-a659d500-e00a-11e8-9ea3-52ec28ee0ded.PNG">

**Comment by ayaanp-dev** [comment]
Nevermind I figured out.

**Comment by jy6666666** [comment]
Hi, 

Could you specify how did you solve this issue? I just happened to have the same issue here.

Thanks

**Comment by ayaanp-dev** [comment]
Ok.  What I had to do is reclone this repository and do pip install -r requirements.txt to install the requirements.  You should have tensorflow and the requirements.
